---
- name: Restart restake.timer
  service:
    name: restake.timer
    state: restarted
  listen: "restart restake.timer"

- name: Start docker
  service:
    name: docker
    state: started
  listen: "start docker"
